### ISSUE TITLE
Moolticute does not correctly detect device if it was connected before Moolticute started (MP Mini/Windows)

### ISSUE THREAD

**Issue by ilmiont** [mooltipass/moolticute#441]
I leave my Mooltipass Mini permanently connected to my desktop over USB. I have Moolticute set to start with Windows.

**Issue description**

After log in, Moolticute starts automatically as intended, but does not properly detect the Mooltipass device.

- The tray icon says "No mooltipass connected".
- The app itself shows default settings for "Device Settings".
- The other app pages, "Credentials" / "Files" etc., *do* appear to be aware a Mooltipass is connected – they show the e.g. "Enter Credentials Management Mode" button, as if the device was unlocked (even if it's actually locked), but clicking never displays the request on the Mooltipass.
- As the daemon doesn't detect the device properly, the browser extension also doesn't work.

These symptoms persist irrespective of whether the connected Mooltipass is locked or unlocked at the time the Moolticute app/daemon start.

**Recovering into a working state**

When in this bad state, the only way to get everything working is to:

1. Disconnect Mooltipass USB
2. Restart daemon from the tray icon
3. Reconnect the Mooltipass.

*Restarting the daemon, without disconnecting the Mooltipass, does not work.*

**A further note**

One point to note is that, very occasionally, everything does work as normal after startup (but this has happened to me only once this week). This leaves me to suspect the Moolticute app/daemon is perhaps seeing too many devices or attempting connection to the wrong device when launching at startup, since the system will be registering multiple new USBs in a short space of time. However, this is speculation and I do not want to deviate further from the objective nature of this issue.

**Logs**

The log from the Moolticute app for today's boot is attached to this issue (see last line of this issue). I believe the first line of the log is the very first message after app startup. For this run, the Mooltipass was already connected (and was locked), and Moolticute opened automatically after startup.

The log ends after Moolticute has been open for around 30-60 seconds; the remainder of the log (going on indefinitely while the app is open) consists of further `MOOLTIPASS_STATUS (0x00b9)` warnings on a regular interval.

**Summary**

*Expected behaviour*

When booting my device, with the Mooltipass connected and Moolticute set to launch on startup, everything should "just work" when I reach the desktop, whether the Mooltipass is locked or unlocked.

*Actual behaviour*

Almost without exception, starting my device with the Mooltipass already connected, whether locked or unlocked, results in the daemon not properly detecting the Mooltipass, and the Mooltipass cannot be used until it is disconnected, the daemon restarted, and then reconnected.

[mplog.txt](https://github.com/mooltipass/moolticute/files/3137238/mplog.txt)

**Comment by raoulh** [comment]
Thanks for your report. Could you try again by using another USB cable?

**Comment by ilmiont** [comment]
I will try that tomorrow on my main desktop (restarting midway through a work day is painful for me).

I just did an experiment on another device though, and found everything did work as expected upon startup with the Mooltipass connected. The Mooltipass was the only device connected over USB.

My main desktop has a few other USBs (and devices which appear as USBs) so possible there is some kind of conflict going on. I'll report back tomorrow with any more information I can get once I've rebooted a few more times.

As I mentioned in the main issue description, *sometimes* but very rarely everything does work. 

But probably > 9 times out of 10, I have to unplug the Mooltipass and restart the daemon to get it working properly.

**Comment by ilmiont** [comment]
Same results this morning on my desktop.

Mooltipass connected at startup (different USB cable) and unlocked (same procedure as worked as expected on my Surface yesterday).

Device again not detected by the app; the daemon logs are essentially the same as those I uploaded above.

**Comment by limpkin** [comment]
@ilmiont could you try installing the latest beta and see if the problem still persists there? https://betas.themooltipass.com/v0.41.6-testing/

**Comment by ilmiont** [comment]
@limpkin will do and will report back tomorrow/as soon as I get a chance to verify if there's a change in the behaviour.

**Comment by ilmiont** [comment]
@limpkin I'm not seeing any change in behaviour in v0.41.6 or v0.41.7 betas on my known affected device.  The daemon logs look the same as I've uploaded before.

Whether Mooltipass is locked or unlocked at Windows login, it is not detected by Moolticute, and I have to disconnect/restart daemon/reconnect still.

**Comment by limpkin** [comment]
that's very odd... do you have this issue on other computers?

**Comment by ilmiont** [comment]
I've only tried on two devices so far (only ever used Mooltipass with these two) but can try with others.

It all seems to work as expected on my Surface (W10 1809 / no other USB devices).

My desktop PC (W10 1803 / several other USBs as previously stated) experiences this pretty much every reboot; as previously described, occasionally it does work normally though... but 9 out of 10 times, I'll hit this issue.

I'm thinking I might need to set some time aside and try booting with a minimal set of devices attached; see if I can identify a USB which might be conflicting.

Do you have any ideas of things I could be trying?

**Comment by limpkin** [comment]
Hey there!
We've just released in our beta channel a new version that solves a very similar bug... could you update to 41.9 and give it a go?

**Comment by ilmiont** [comment]
Hello,

Unfortunately, I'm not seeing any change in this version either.

Issue still remains for me exactly as described here.

I've prepared a short video with captions to illustrate exactly what I'm seeing: 

https://youtu.be/Rg1ljdfbTyA

Please do let me know if you need any more information or there's anything I should try. I keep meaning to set some time aside to try and look further into this and try different combinations of connected USBs, but I'm very busy right now and still not got around to it.

The issue remains same as described... until the MP is disconnected, the daemon restarted, and MP then reconnected, nothing in the app works and the daemon log is filled with "handle invalid" errors.

**Comment by limpkin** [comment]
damn... that's really odd... it'd be interesting to try and unplug all your usb devices and see if this problem remains.

**Comment by ilmiont** [comment]
Hello,

I believe I have found the root cause of the issue: it appears as though the TrackIR software is the cause of the conflict.

https://www.naturalpoint.com/trackir/

(TrackIR is an infrared head-tracking system used as a game controller.)

When TrackIR launches on boot, and before Moolticute, Moolticute exhibits the behaviour described in this issue.

With TrackIR disabled as a startup item, Moolticute appears to work normally.

I didn't make any changes to my connected USB devices, and the TrackIR sensor itself was disconnected for these tests. Just having TrackIR running before Moolticute is running causes this issues; if I disable Moolticute from starting at boot, start TrackIR, and then start Moolticute, I still see this issue until I disconnect Mooltipass/restart daemon (in that order).

Therefore it appears as though the TrackIR software is introducing some conflict when it is running which prevents Moolticute from communicating with the Mooltipass, if the Mooltipass was already connected to the device.

Obviously I can mitigate this for the timebeing by disabling TrackIR from starting on-boot. If Moolticute launches first, and then I start TrackIR, there don't appear to be any issues.

I'll report back if I observe any more changes, but in the meantime, I hope this gives you something to go on. I have no idae though what the TrackIR software is doing to be causing this conflict.

**Comment by limpkin** [comment]
Thanks for the update @ilmiont !

**Comment by raoulh** [comment]
Thanks for the find. This makes me think of something. Could you please try with this older Moolticute release please:

https://github.com/mooltipass/moolticute/releases/download/v0.30.8/moolticute_setup_v0.30.8.exe

**Comment by ilmiont** [comment]
Hi @raoulh, can confirm I'm not seeing the issue with Moolticute v0.30.8 and TrackIR re-enabled on startup. Everything seems to be working normally after a couple of reboots.

**Comment by limpkin** [comment]
what should we do with this issue now that we've identified that trackIR is doing something it shouldn't? :)

**Comment by ilmiont** [comment]
I'm still running v0.30.8 for timebeing which does not conflict with TrackIR.

I take it the change introduced to Moolticute between v0.30.8 and the current (conflicting) versions is non-revertable then?

**Comment by limpkin** [comment]
In short, trackir software is doing something it shouldn't USB-wise and preventing us to exclusively open the mooltipass communication channel. Therefore, there isn't anything we can do anything on our side :/
